2016-12-27 12:58:54 [main] INFO  c.j.core.server.JMonitorServer [JMonitorServer.java:21] - JMonitorServer starting...
2016-12-27 12:58:54 [main] INFO  c.j.core.message.consume.Period [Period.java:69] - Starting 4 tasks in period [2016-12-27 12:00:00, 2016-12-27 12:59:59]
2016-12-27 12:58:54 [Thread-4] INFO  c.j.core.message.consume.Period [Period.java:69] - Starting 4 tasks in period [2016-12-27 13:00:00, 2016-12-27 13:59:59]
2016-12-27 12:58:54 [MLog-Init-Reporter] INFO  com.mchange.v2.log.MLog [Slf4jMLog.java:212] - MLog clients using slf4j logging.
2016-12-27 12:58:55 [Thread-10] INFO  com.mchange.v2.c3p0.C3P0Registry [Slf4jMLog.java:212] - Initializing c3p0-0.9.5.2 [built 08-December-2015 22:06:04 -0800; debug? true; trace: 10]
2016-12-27 12:58:55 [Thread-10] INFO  c.m.v.c.i.AbstractPoolBackedDataSource [Slf4jMLog.java:212] - Initializing c3p0 pool... com.mchange.v2.c3p0.ComboPooledDataSource [ acquireIncrement -> 5, acquireRetryAttempts -> 30, acquireRetryDelay -> 1000, autoCommitOnClose -> false, automaticTestTable -> null, breakAfterAcquireFailure -> false, checkoutTimeout -> 0, connectionCustomizerClassName -> null, connectionTesterClassName -> com.mchange.v2.c3p0.impl.DefaultConnectionTester, contextClassLoaderSource -> caller, dataSourceName -> 1hge1d19lhdqyjhnu7euv|13fe459, debugUnreturnedConnectionStackTraces -> false, description -> null, driverClass -> com.mysql.jdbc.Driver, extensions -> {}, factoryClassLocation -> null, forceIgnoreUnresolvedTransactions -> false, forceSynchronousCheckins -> false, forceUseNamedDriverClass -> false, identityToken -> 1hge1d19lhdqyjhnu7euv|13fe459, idleConnectionTestPeriod -> 0, initialPoolSize -> 5, jdbcUrl -> jdbc:mysql://localhost:3306/jmonitor?useSSL=false, maxAdministrativeTaskTime -> 0, maxConnectionAge -> 0, maxIdleTime -> 240, maxIdleTimeExcessConnections -> 0, maxPoolSize -> 20, maxStatements -> 0, maxStatementsPerConnection -> 0, minPoolSize -> 5, numHelperThreads -> 3, preferredTestQuery -> null, privilegeSpawnedThreads -> false, properties -> {user=******, password=******}, propertyCycle -> 0, statementCacheNumDeferredCloseThreads -> 0, testConnectionOnCheckin -> false, testConnectionOnCheckout -> false, unreturnedConnectionTimeout -> 0, userOverrides -> {}, usesTraditionalReflectiveProxies -> false ]
2016-12-27 12:58:55 [Thread-5] INFO  c.j.core.message.io.MessageReceiver [MessageReceiver.java:103] - start netty server OK !
2016-12-27 12:59:12 [Thread-0] ERROR c.j.core.message.io.MessageSender [MessageSender.java:75] - Connected to server at /127.0.0.1:2280
2016-12-27 12:59:12 [Thread-0] INFO  com.jmonitor.core.JMonitor [JMonitor.java:24] - JMonitor start !
2016-12-27 12:59:12 [nioEventLoopGroup-3-1] ERROR c.j.core.message.consume.Period [Period.java:57] - no PeriodTask found for ProblemsAnalyzer
2016-12-27 12:59:16 [nioEventLoopGroup-3-1] WARN  i.n.channel.DefaultChannelPipeline [Slf4JLogger.java:151] - An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
java.io.IOException: 远程主机强迫关闭了一个现有的连接。
	at sun.nio.ch.SocketDispatcher.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1100)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:367)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:118)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:610)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:551)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:465)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:437)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:873)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
	at java.lang.Thread.run(Thread.java:745)
2016-12-27 13:00:14 [main] INFO  c.j.core.server.JMonitorServer [JMonitorServer.java:21] - JMonitorServer starting...
2016-12-27 13:00:14 [main] INFO  c.j.core.message.consume.Period [Period.java:69] - Starting 4 tasks in period [2016-12-27 13:00:00, 2016-12-27 13:59:59]
2016-12-27 13:00:14 [MLog-Init-Reporter] INFO  com.mchange.v2.log.MLog [Slf4jMLog.java:212] - MLog clients using slf4j logging.
2016-12-27 13:00:14 [Thread-6] INFO  com.mchange.v2.c3p0.C3P0Registry [Slf4jMLog.java:212] - Initializing c3p0-0.9.5.2 [built 08-December-2015 22:06:04 -0800; debug? true; trace: 10]
2016-12-27 13:00:14 [Thread-6] INFO  c.m.v.c.i.AbstractPoolBackedDataSource [Slf4jMLog.java:212] - Initializing c3p0 pool... com.mchange.v2.c3p0.ComboPooledDataSource [ acquireIncrement -> 5, acquireRetryAttempts -> 30, acquireRetryDelay -> 1000, autoCommitOnClose -> false, automaticTestTable -> null, breakAfterAcquireFailure -> false, checkoutTimeout -> 0, connectionCustomizerClassName -> null, connectionTesterClassName -> com.mchange.v2.c3p0.impl.DefaultConnectionTester, contextClassLoaderSource -> caller, dataSourceName -> 1hge1d19lhdsnnsjbau45|1dd859f, debugUnreturnedConnectionStackTraces -> false, description -> null, driverClass -> com.mysql.jdbc.Driver, extensions -> {}, factoryClassLocation -> null, forceIgnoreUnresolvedTransactions -> false, forceSynchronousCheckins -> false, forceUseNamedDriverClass -> false, identityToken -> 1hge1d19lhdsnnsjbau45|1dd859f, idleConnectionTestPeriod -> 0, initialPoolSize -> 5, jdbcUrl -> jdbc:mysql://localhost:3306/jmonitor?useSSL=false, maxAdministrativeTaskTime -> 0, maxConnectionAge -> 0, maxIdleTime -> 240, maxIdleTimeExcessConnections -> 0, maxPoolSize -> 20, maxStatements -> 0, maxStatementsPerConnection -> 0, minPoolSize -> 5, numHelperThreads -> 3, preferredTestQuery -> null, privilegeSpawnedThreads -> false, properties -> {user=******, password=******}, propertyCycle -> 0, statementCacheNumDeferredCloseThreads -> 0, testConnectionOnCheckin -> false, testConnectionOnCheckout -> false, unreturnedConnectionTimeout -> 0, userOverrides -> {}, usesTraditionalReflectiveProxies -> false ]
2016-12-27 13:00:14 [Thread-5] INFO  c.j.core.message.io.MessageReceiver [MessageReceiver.java:103] - start netty server OK !
2016-12-27 13:00:20 [Thread-0] INFO  c.j.core.message.io.MessageSender [MessageSender.java:75] - Connected to server at /127.0.0.1:2280
2016-12-27 13:00:20 [Thread-0] INFO  com.jmonitor.core.JMonitor [JMonitor.java:24] - JMonitor start !
2016-12-27 13:00:20 [nioEventLoopGroup-3-1] ERROR c.j.core.message.consume.Period [Period.java:57] - no PeriodTask found for ProblemsAnalyzer
2016-12-27 13:00:30 [nioEventLoopGroup-3-1] ERROR c.j.core.message.consume.Period [Period.java:57] - no PeriodTask found for ProblemsAnalyzer
2016-12-27 13:00:31 [nioEventLoopGroup-3-1] WARN  i.n.channel.DefaultChannelPipeline [Slf4JLogger.java:151] - An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
java.io.IOException: 远程主机强迫关闭了一个现有的连接。
	at sun.nio.ch.SocketDispatcher.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1100)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:367)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:118)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:610)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:551)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:465)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:437)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:873)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
	at java.lang.Thread.run(Thread.java:745)
2016-12-27 13:01:11 [main] INFO  c.j.core.server.JMonitorServer [JMonitorServer.java:21] - JMonitorServer starting...
2016-12-27 13:01:11 [main] INFO  c.j.core.message.consume.Period [Period.java:69] - Starting 4 tasks in period [2016-12-27 13:00:00, 2016-12-27 13:59:59]
2016-12-27 13:01:11 [MLog-Init-Reporter] INFO  com.mchange.v2.log.MLog [Slf4jMLog.java:212] - MLog clients using slf4j logging.
2016-12-27 13:01:11 [Thread-6] INFO  com.mchange.v2.c3p0.C3P0Registry [Slf4jMLog.java:212] - Initializing c3p0-0.9.5.2 [built 08-December-2015 22:06:04 -0800; debug? true; trace: 10]
2016-12-27 13:01:11 [Thread-6] INFO  c.m.v.c.i.AbstractPoolBackedDataSource [Slf4jMLog.java:212] - Initializing c3p0 pool... com.mchange.v2.c3p0.ComboPooledDataSource [ acquireIncrement -> 5, acquireRetryAttempts -> 30, acquireRetryDelay -> 1000, autoCommitOnClose -> false, automaticTestTable -> null, breakAfterAcquireFailure -> false, checkoutTimeout -> 0, connectionCustomizerClassName -> null, connectionTesterClassName -> com.mchange.v2.c3p0.impl.DefaultConnectionTester, contextClassLoaderSource -> caller, dataSourceName -> 1hge1d19lhdtvwr1eeyzzv|1d9bfa3, debugUnreturnedConnectionStackTraces -> false, description -> null, driverClass -> com.mysql.jdbc.Driver, extensions -> {}, factoryClassLocation -> null, forceIgnoreUnresolvedTransactions -> false, forceSynchronousCheckins -> false, forceUseNamedDriverClass -> false, identityToken -> 1hge1d19lhdtvwr1eeyzzv|1d9bfa3, idleConnectionTestPeriod -> 0, initialPoolSize -> 5, jdbcUrl -> jdbc:mysql://localhost:3306/jmonitor?useSSL=false, maxAdministrativeTaskTime -> 0, maxConnectionAge -> 0, maxIdleTime -> 240, maxIdleTimeExcessConnections -> 0, maxPoolSize -> 20, maxStatements -> 0, maxStatementsPerConnection -> 0, minPoolSize -> 5, numHelperThreads -> 3, preferredTestQuery -> null, privilegeSpawnedThreads -> false, properties -> {user=******, password=******}, propertyCycle -> 0, statementCacheNumDeferredCloseThreads -> 0, testConnectionOnCheckin -> false, testConnectionOnCheckout -> false, unreturnedConnectionTimeout -> 0, userOverrides -> {}, usesTraditionalReflectiveProxies -> false ]
2016-12-27 13:01:11 [Thread-5] INFO  c.j.core.message.io.MessageReceiver [MessageReceiver.java:103] - start netty server OK !
2016-12-27 13:01:16 [Thread-0] INFO  c.j.core.message.io.MessageSender [MessageSender.java:75] - Connected to server at /127.0.0.1:2280
2016-12-27 13:01:16 [Thread-0] INFO  com.jmonitor.core.JMonitor [JMonitor.java:24] - JMonitor start !
2016-12-27 13:01:16 [nioEventLoopGroup-3-1] ERROR c.j.core.message.consume.Period [Period.java:57] - no PeriodTask found for ProblemsAnalyzer
2016-12-27 13:01:26 [nioEventLoopGroup-3-1] ERROR c.j.core.message.consume.Period [Period.java:57] - no PeriodTask found for ProblemsAnalyzer
2016-12-27 13:01:27 [nioEventLoopGroup-3-1] WARN  i.n.channel.DefaultChannelPipeline [Slf4JLogger.java:151] - An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
java.io.IOException: 远程主机强迫关闭了一个现有的连接。
	at sun.nio.ch.SocketDispatcher.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1100)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:367)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:118)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:610)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:551)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:465)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:437)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:873)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
	at java.lang.Thread.run(Thread.java:745)
2016-12-27 13:01:38 [main] INFO  c.j.core.server.JMonitorServer [JMonitorServer.java:21] - JMonitorServer starting...
2016-12-27 13:01:38 [main] INFO  c.j.core.message.consume.Period [Period.java:69] - Starting 4 tasks in period [2016-12-27 13:00:00, 2016-12-27 13:59:59]
2016-12-27 13:01:38 [MLog-Init-Reporter] INFO  com.mchange.v2.log.MLog [Slf4jMLog.java:212] - MLog clients using slf4j logging.
2016-12-27 13:01:38 [Thread-6] INFO  com.mchange.v2.c3p0.C3P0Registry [Slf4jMLog.java:212] - Initializing c3p0-0.9.5.2 [built 08-December-2015 22:06:04 -0800; debug? true; trace: 10]
2016-12-27 13:01:38 [Thread-6] INFO  c.m.v.c.i.AbstractPoolBackedDataSource [Slf4jMLog.java:212] - Initializing c3p0 pool... com.mchange.v2.c3p0.ComboPooledDataSource [ acquireIncrement -> 5, acquireRetryAttempts -> 30, acquireRetryDelay -> 1000, autoCommitOnClose -> false, automaticTestTable -> null, breakAfterAcquireFailure -> false, checkoutTimeout -> 0, connectionCustomizerClassName -> null, connectionTesterClassName -> com.mchange.v2.c3p0.impl.DefaultConnectionTester, contextClassLoaderSource -> caller, dataSourceName -> 1hge1d19lhdugwwixvjdl|123ca3, debugUnreturnedConnectionStackTraces -> false, description -> null, driverClass -> com.mysql.jdbc.Driver, extensions -> {}, factoryClassLocation -> null, forceIgnoreUnresolvedTransactions -> false, forceSynchronousCheckins -> false, forceUseNamedDriverClass -> false, identityToken -> 1hge1d19lhdugwwixvjdl|123ca3, idleConnectionTestPeriod -> 0, initialPoolSize -> 5, jdbcUrl -> jdbc:mysql://localhost:3306/jmonitor?useSSL=false, maxAdministrativeTaskTime -> 0, maxConnectionAge -> 0, maxIdleTime -> 240, maxIdleTimeExcessConnections -> 0, maxPoolSize -> 20, maxStatements -> 0, maxStatementsPerConnection -> 0, minPoolSize -> 5, numHelperThreads -> 3, preferredTestQuery -> null, privilegeSpawnedThreads -> false, properties -> {user=******, password=******}, propertyCycle -> 0, statementCacheNumDeferredCloseThreads -> 0, testConnectionOnCheckin -> false, testConnectionOnCheckout -> false, unreturnedConnectionTimeout -> 0, userOverrides -> {}, usesTraditionalReflectiveProxies -> false ]
2016-12-27 13:01:39 [Thread-5] INFO  c.j.core.message.io.MessageReceiver [MessageReceiver.java:103] - start netty server OK !
2016-12-27 13:01:41 [Thread-1] INFO  c.j.core.message.io.MessageSender [MessageSender.java:75] - Connected to server at /127.0.0.1:2280
2016-12-27 13:01:41 [Thread-1] INFO  com.jmonitor.core.JMonitor [JMonitor.java:24] - JMonitor start !
2016-12-27 13:01:42 [nioEventLoopGroup-3-1] ERROR c.j.core.message.consume.Period [Period.java:57] - no PeriodTask found for ProblemsAnalyzer
2016-12-27 13:01:51 [nioEventLoopGroup-3-1] ERROR c.j.core.message.consume.Period [Period.java:57] - no PeriodTask found for ProblemsAnalyzer
2016-12-27 13:02:01 [nioEventLoopGroup-3-1] ERROR c.j.core.message.consume.Period [Period.java:57] - no PeriodTask found for ProblemsAnalyzer
2016-12-27 13:02:11 [nioEventLoopGroup-3-1] ERROR c.j.core.message.consume.Period [Period.java:57] - no PeriodTask found for ProblemsAnalyzer
2016-12-27 13:02:21 [nioEventLoopGroup-3-1] ERROR c.j.core.message.consume.Period [Period.java:57] - no PeriodTask found for ProblemsAnalyzer
2016-12-27 13:02:31 [nioEventLoopGroup-3-1] ERROR c.j.core.message.consume.Period [Period.java:57] - no PeriodTask found for ProblemsAnalyzer
2016-12-27 13:02:41 [nioEventLoopGroup-3-1] ERROR c.j.core.message.consume.Period [Period.java:57] - no PeriodTask found for ProblemsAnalyzer
2016-12-27 13:02:51 [nioEventLoopGroup-3-1] ERROR c.j.core.message.consume.Period [Period.java:57] - no PeriodTask found for ProblemsAnalyzer
2016-12-27 13:03:01 [nioEventLoopGroup-3-1] ERROR c.j.core.message.consume.Period [Period.java:57] - no PeriodTask found for ProblemsAnalyzer
2016-12-27 13:03:11 [nioEventLoopGroup-3-1] ERROR c.j.core.message.consume.Period [Period.java:57] - no PeriodTask found for ProblemsAnalyzer
2016-12-27 13:03:21 [nioEventLoopGroup-3-1] ERROR c.j.core.message.consume.Period [Period.java:57] - no PeriodTask found for ProblemsAnalyzer
2016-12-27 13:03:31 [nioEventLoopGroup-3-1] ERROR c.j.core.message.consume.Period [Period.java:57] - no PeriodTask found for ProblemsAnalyzer
2016-12-27 13:03:41 [nioEventLoopGroup-3-1] ERROR c.j.core.message.consume.Period [Period.java:57] - no PeriodTask found for ProblemsAnalyzer
2016-12-27 13:03:51 [nioEventLoopGroup-3-1] ERROR c.j.core.message.consume.Period [Period.java:57] - no PeriodTask found for ProblemsAnalyzer
2016-12-27 13:04:11 [nioEventLoopGroup-3-1] ERROR c.j.core.message.consume.Period [Period.java:57] - no PeriodTask found for ProblemsAnalyzer
2016-12-27 13:04:21 [nioEventLoopGroup-3-1] ERROR c.j.core.message.consume.Period [Period.java:57] - no PeriodTask found for ProblemsAnalyzer
2016-12-27 13:04:31 [nioEventLoopGroup-3-1] ERROR c.j.core.message.consume.Period [Period.java:57] - no PeriodTask found for ProblemsAnalyzer
2016-12-27 13:04:42 [nioEventLoopGroup-3-1] ERROR c.j.core.message.consume.Period [Period.java:57] - no PeriodTask found for ProblemsAnalyzer
2016-12-27 13:04:52 [nioEventLoopGroup-3-1] ERROR c.j.core.message.consume.Period [Period.java:57] - no PeriodTask found for ProblemsAnalyzer
2016-12-27 13:05:02 [nioEventLoopGroup-3-1] ERROR c.j.core.message.consume.Period [Period.java:57] - no PeriodTask found for ProblemsAnalyzer
2016-12-27 13:05:12 [nioEventLoopGroup-3-1] ERROR c.j.core.message.consume.Period [Period.java:57] - no PeriodTask found for ProblemsAnalyzer
2016-12-27 13:05:22 [nioEventLoopGroup-3-1] ERROR c.j.core.message.consume.Period [Period.java:57] - no PeriodTask found for ProblemsAnalyzer
2016-12-27 13:05:32 [nioEventLoopGroup-3-1] ERROR c.j.core.message.consume.Period [Period.java:57] - no PeriodTask found for ProblemsAnalyzer
2016-12-27 13:05:42 [nioEventLoopGroup-3-1] ERROR c.j.core.message.consume.Period [Period.java:57] - no PeriodTask found for ProblemsAnalyzer
2016-12-27 13:05:46 [Thread-3] WARN  i.n.channel.DefaultChannelPipeline [Slf4JLogger.java:151] - An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
java.io.IOException: 远程主机强迫关闭了一个现有的连接。
	at sun.nio.ch.SocketDispatcher.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1100)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:367)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:118)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:610)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:551)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:465)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:437)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:873)
	at java.lang.Thread.run(Thread.java:745)
2016-12-27 13:05:57 [main] INFO  c.j.core.server.JMonitorServer [JMonitorServer.java:21] - JMonitorServer starting...
2016-12-27 13:05:57 [main] INFO  c.j.core.message.consume.Period [Period.java:69] - Starting 4 tasks in period [2016-12-27 13:00:00, 2016-12-27 13:59:59]
2016-12-27 13:05:57 [MLog-Init-Reporter] INFO  com.mchange.v2.log.MLog [Slf4jMLog.java:212] - MLog clients using slf4j logging.
2016-12-27 13:05:57 [Thread-6] INFO  com.mchange.v2.c3p0.C3P0Registry [Slf4jMLog.java:212] - Initializing c3p0-0.9.5.2 [built 08-December-2015 22:06:04 -0800; debug? true; trace: 10]
2016-12-27 13:05:57 [Thread-6] INFO  c.m.v.c.i.AbstractPoolBackedDataSource [Slf4jMLog.java:212] - Initializing c3p0 pool... com.mchange.v2.c3p0.ComboPooledDataSource [ acquireIncrement -> 5, acquireRetryAttempts -> 30, acquireRetryDelay -> 1000, autoCommitOnClose -> false, automaticTestTable -> null, breakAfterAcquireFailure -> false, checkoutTimeout -> 0, connectionCustomizerClassName -> null, connectionTesterClassName -> com.mchange.v2.c3p0.impl.DefaultConnectionTester, contextClassLoaderSource -> caller, dataSourceName -> 1hge1d19lhe00cykpzm9l|86f919, debugUnreturnedConnectionStackTraces -> false, description -> null, driverClass -> com.mysql.jdbc.Driver, extensions -> {}, factoryClassLocation -> null, forceIgnoreUnresolvedTransactions -> false, forceSynchronousCheckins -> false, forceUseNamedDriverClass -> false, identityToken -> 1hge1d19lhe00cykpzm9l|86f919, idleConnectionTestPeriod -> 0, initialPoolSize -> 5, jdbcUrl -> jdbc:mysql://localhost:3306/jmonitor?useSSL=false, maxAdministrativeTaskTime -> 0, maxConnectionAge -> 0, maxIdleTime -> 240, maxIdleTimeExcessConnections -> 0, maxPoolSize -> 20, maxStatements -> 0, maxStatementsPerConnection -> 0, minPoolSize -> 5, numHelperThreads -> 3, preferredTestQuery -> null, privilegeSpawnedThreads -> false, properties -> {user=******, password=******}, propertyCycle -> 0, statementCacheNumDeferredCloseThreads -> 0, testConnectionOnCheckin -> false, testConnectionOnCheckout -> false, unreturnedConnectionTimeout -> 0, userOverrides -> {}, usesTraditionalReflectiveProxies -> false ]
2016-12-27 13:05:57 [Thread-5] INFO  c.j.core.message.io.MessageReceiver [MessageReceiver.java:103] - start netty server OK !
2016-12-27 13:06:00 [Thread-1] INFO  c.j.core.message.io.MessageSender [MessageSender.java:75] - Connected to server at /127.0.0.1:2280
2016-12-27 13:06:00 [Thread-1] INFO  com.jmonitor.core.JMonitor [JMonitor.java:24] - JMonitor start !
2016-12-27 13:16:00 [nioEventLoopGroup-3-1] ERROR io.netty.util.ResourceLeakDetector [Slf4JLogger.java:176] - LEAK: ByteBuf.release() was not called before it's garbage-collected. Enable advanced leak reporting to find out where the leak occurred. To enable advanced leak reporting, specify the JVM option '-Dio.netty.leakDetection.level=advanced' or call ResourceLeakDetector.setLevel() See http://netty.io/wiki/reference-counted-objects.html for more information.
